---
- hosts: all
  become: yes
  tasks:
   - name: Install Java 1.8
     apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
   - name: add group "tomcat"
     group:
      name: tomcat
   - name: add user "tomcat"
     user:
      name: tomcat
      group: tomcat
   - name: Download Tomcat
     #get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
     get_url: url=https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.65/bin/apache-tomcat-8.5.65.tar.gz dest=/opt/apache-tomcat-8.5.65.tar.gz
   - name: Extract archive
     command: /bin/tar xvf /opt/apache-tomcat-8.5.65.tar.gz -C /opt
   - name: create tomcat home
     command: mv /opt/apache-tomcat-8.5.65 /opt/tomcat
   - name: Change ownership of Tomcat installation
     file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: 0755
      state: directory
      recurse: yes
   - name: Start Tomcat
     command: "nohup /opt/tomcat/bin/startup.sh"
     become_user: tomcat
